/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.cvapp;

import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author hasan
 */
public class CreateNewPassword extends javax.swing.JFrame {

    String newEmailPassword = "";

    /**
     * Creates new form CreateNewPassword
     */
    public CreateNewPassword(String incomingEmail) {
        initComponents();
        setTitle("Create New Password Screen");
        newEmailPassword = incomingEmail;

    }

    class JPanelGradient extends JPanel {
//I made the part below to make a background with transition between 2 colors.
        protected void paintComponent(Graphics g) {
            Graphics2D g2d = (Graphics2D) g;
            int width = getWidth();
            int height = getHeight();

            Color color_1 = new Color(251, 188, 5);
            Color color_2 = new Color(234, 67, 53);

            GradientPaint gp = new GradientPaint(0, 0, color_1, 180, height, color_2);
            g2d.setPaint(gp);
            g2d.fillRect(0, 0, width, height);

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new JPanelGradient();
        lbl_messageNewPassword = new javax.swing.JLabel();
        lbl_newPasswordIcon = new javax.swing.JLabel();
        lbl_newPasswordIcon1 = new javax.swing.JLabel();
        txtFirstPassword = new javax.swing.JPasswordField();
        txtSecondPassword = new javax.swing.JPasswordField();
        chckBox_showEnteredPassword = new javax.swing.JCheckBox();
        btn_SaveNewPassword = new javax.swing.JButton();
        btn_goBackToLoginScreen = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        lbl_messageNewPassword.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbl_messageNewPassword.setText("Please enter your new password");

        lbl_newPasswordIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\hasan\\Desktop\\FSMVÜ\\CV UYGULAMASI(FİNAL)\\padlock.png")); // NOI18N

        lbl_newPasswordIcon1.setIcon(new javax.swing.ImageIcon("C:\\Users\\hasan\\Desktop\\FSMVÜ\\CV UYGULAMASI(FİNAL)\\padlock.png")); // NOI18N

        chckBox_showEnteredPassword.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        chckBox_showEnteredPassword.setText("Show password");
        chckBox_showEnteredPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chckBox_showEnteredPasswordActionPerformed(evt);
            }
        });

        btn_SaveNewPassword.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn_SaveNewPassword.setText("Save new password");
        btn_SaveNewPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SaveNewPasswordActionPerformed(evt);
            }
        });

        btn_goBackToLoginScreen.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn_goBackToLoginScreen.setText("Return to login screen");
        btn_goBackToLoginScreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_goBackToLoginScreenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(180, Short.MAX_VALUE)
                .addComponent(lbl_messageNewPassword)
                .addGap(141, 141, 141))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_SaveNewPassword))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(80, 80, 80)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lbl_newPasswordIcon1)
                                        .addComponent(lbl_newPasswordIcon))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtFirstPassword)
                                        .addComponent(txtSecondPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)))
                                .addComponent(btn_goBackToLoginScreen)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGap(28, 28, 28)
                            .addComponent(chckBox_showEnteredPassword))))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lbl_messageNewPassword)
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtFirstPassword)
                    .addComponent(lbl_newPasswordIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_newPasswordIcon1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtSecondPassword))
                .addGap(18, 18, 18)
                .addComponent(chckBox_showEnteredPassword)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_SaveNewPassword)
                    .addComponent(btn_goBackToLoginScreen))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void chckBox_showEnteredPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chckBox_showEnteredPasswordActionPerformed
        // TODO add your handling code here:
        //        to make the password visible when the user wants to see the password
        if (chckBox_showEnteredPassword.isSelected()) {

            txtFirstPassword.setEchoChar((char) 0);
            txtSecondPassword.setEchoChar((char) 0);

        } else {
            txtFirstPassword.setEchoChar('*');
            txtSecondPassword.setEchoChar('*');
        }
    }//GEN-LAST:event_chckBox_showEnteredPasswordActionPerformed

    private void btn_goBackToLoginScreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_goBackToLoginScreenActionPerformed

        //// When Return to login screen is clicked, to close this frame and return to the main login screen.
        LoginFrame LoginFrame = new LoginFrame();
        LoginFrame.setVisible(true);
        LoginFrame.pack();
        LoginFrame.setLocationRelativeTo(null);
        LoginFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();

    }//GEN-LAST:event_btn_goBackToLoginScreenActionPerformed

    private void btn_SaveNewPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SaveNewPasswordActionPerformed
        // TODO add your handling code here:

        Matcher matcher;

        if (txtFirstPassword.getText().isEmpty() || txtSecondPassword.getText().isEmpty()) {

            JOptionPane.showMessageDialog(null, "Please fill in the password fields", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        } else {
            String password = txtFirstPassword.getText();
            String repassword = txtSecondPassword.getText();
            int value = password.compareTo(repassword);
            //password and repassword must be the same...
            //if value = 0 the passwords are the same

            if (value != 0) {

                JOptionPane.showMessageDialog(null, "Please check your password and repassword.\n They must be same. ", "Error", JOptionPane.ERROR_MESSAGE);
                return;

            } else {
                matcher = Pattern.compile("^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)[A-Za-z\\d]{3,}$").matcher(txtFirstPassword.getText());
                if (!matcher.find()) {

                    JOptionPane.showMessageDialog(null, "Password must have least one number,\n and password's lenght not less than 3.\nYour password must like mehmetAk01 ", "Error", JOptionPane.ERROR_MESSAGE);
                    return;

                } else {
                    Connection conn = null;
                    Statement stmt_select = null;

                    try {
                        String email_update = txtFirstPassword.getText();

                        //I did the update process below to save the renewed password to the database.
                        conn = DriverManager.getConnection("jdbc:derby://localhost:1527/CvAppDB", "sa", "as");

                        String query_update_password = "update user_info set user_password = '" + email_update + "' where user_email   = '" + newEmailPassword + "'";
                        PreparedStatement preparedStmt = conn.prepareStatement(query_update_password);

                        // execute the java preparedstatement
                        preparedStmt.executeUpdate();

                        JOptionPane.showMessageDialog(null, "Password updated successfully ", "Information", JOptionPane.INFORMATION_MESSAGE);
                        return;
                    } catch (Exception e) {
                        String exception = e.getMessage();
                    }
                }

            }
        }

    }//GEN-LAST:event_btn_SaveNewPasswordActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        // I want to ask to users when the winwod closing...
        int SelectedOption = JOptionPane.showConfirmDialog(rootPane, "Are you sure you want to close the app?", "Warning", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);

        if (SelectedOption == JOptionPane.YES_OPTION) {
            this.dispose();
        }
        if (SelectedOption == JOptionPane.NO_OPTION) {
            this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateNewPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateNewPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateNewPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateNewPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateNewPassword("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_SaveNewPassword;
    private javax.swing.JButton btn_goBackToLoginScreen;
    private javax.swing.JCheckBox chckBox_showEnteredPassword;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_messageNewPassword;
    private javax.swing.JLabel lbl_newPasswordIcon;
    private javax.swing.JLabel lbl_newPasswordIcon1;
    private javax.swing.JPasswordField txtFirstPassword;
    private javax.swing.JPasswordField txtSecondPassword;
    // End of variables declaration//GEN-END:variables
}
