/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.cvapp;

import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author hasan
 */
public class CvCreate extends javax.swing.JFrame {

    /**
     * Creates new form CvCreate
     */
    String userEmail = "";
    
    public CvCreate(String incomingEmail) {
        initComponents();
        setTitle("Cv Creation Screen");
        updateComboboxExperiences();
        updateComboboxLanguages();
        updateComboboxHobbies();
        
         userEmail = incomingEmail;
        txtField_Email.setText(userEmail);

    }

    //I made the part below to make a background with transition between 2 colors.
    class JPanelGradient extends JPanel {

        protected void paintComponent(Graphics g) {
            Graphics2D g2d = (Graphics2D) g;
            int width = getWidth();
            int height = getHeight();

            Color color_1 = new Color(255, 178, 102);
            Color color_2 = new Color(255, 128, 0);

            GradientPaint gp = new GradientPaint(0, 0, color_1, 180, height, color_2);
            g2d.setPaint(gp);
            g2d.fillRect(0, 0, width, height);

        }

    }

    //update combobox values from database...
    private void updateComboboxExperiences() {
        Connection conn = null;
        Statement stmt_select = null;
        String sql = "select * from EXPERIENCES";
        try {
            conn = DriverManager.getConnection("jdbc:derby://localhost:1527/CvAppDB", "sa", "as");
            stmt_select = conn.createStatement();

            ResultSet rs_ex = stmt_select.executeQuery(sql);
            while (rs_ex.next()) {
                comboBox_experiences.addItem(rs_ex.getString(1));
            }

        } catch (Exception e) {
        }
    }

    private void updateComboboxLanguages() {
        Connection conn = null;
        Statement stmt_select = null;
        String sql = "select * from LANGUAGES";
        try {
            conn = DriverManager.getConnection("jdbc:derby://localhost:1527/CvAppDB", "sa", "as");
            stmt_select = conn.createStatement();

            ResultSet rs_ex = stmt_select.executeQuery(sql);
            while (rs_ex.next()) {
                comboBox_languages.addItem(rs_ex.getString(1));
            }

        } catch (Exception e) {
        }
    }

    private void updateComboboxHobbies() {
        Connection conn = null;
        Statement stmt_select = null;
        String sql = "select * from INTEREST_AND_HOBBIES";
        try {
            conn = DriverManager.getConnection("jdbc:derby://localhost:1527/CvAppDB", "sa", "as");
            stmt_select = conn.createStatement();

            ResultSet rs_ex = stmt_select.executeQuery(sql);
            while (rs_ex.next()) {
                comboBoc_Hobbies.addItem(rs_ex.getString(1));
            }

        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbed_pane = new javax.swing.JTabbedPane();
        pnl_personal = new JPanelGradient();
        pnl_PersonalInformation = new JPanelGradient();
        lbl_firstname = new javax.swing.JLabel();
        lbl_Surname = new javax.swing.JLabel();
        lbl_Email = new javax.swing.JLabel();
        txtField_Email = new javax.swing.JTextField();
        txtField_firstName = new javax.swing.JTextField();
        txtField_Surname = new javax.swing.JTextField();
        lbl_phoneNumber = new javax.swing.JLabel();
        txtField_phoneNumber = new javax.swing.JTextField();
        lbl_city = new javax.swing.JLabel();
        cmboBox_Cities = new javax.swing.JComboBox<>();
        lbl_DateOfBirth = new javax.swing.JLabel();
        cmbBox_Day = new javax.swing.JComboBox<>();
        cmbBox_Months = new javax.swing.JComboBox<>();
        lbl_Gender = new javax.swing.JLabel();
        rbtn_male = new javax.swing.JRadioButton();
        rbtn_female = new javax.swing.JRadioButton();
        cmbBox_Year = new javax.swing.JComboBox<>();
        btn_NextStepExperiences = new javax.swing.JButton();
        jlabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lbl_age = new javax.swing.JLabel();
        lbl_ageIcon1 = new javax.swing.JLabel();
        slider_age = new javax.swing.JSlider();
        spinner_age = new javax.swing.JSpinner();
        btn_BacktoTheLoginFrame = new javax.swing.JButton();
        pnl_experiences = new JPanelGradient();
        jPanel2 = new JPanelGradient();
        lbl_experiencesIcon = new javax.swing.JLabel();
        btn_add = new javax.swing.JButton();
        comboBox_experiences = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        List_Experiences = new javax.swing.JList<>();
        btn_delete = new javax.swing.JButton();
        lbl_languagesIcon = new javax.swing.JLabel();
        comboBox_languages = new javax.swing.JComboBox<>();
        btn_addLanguages = new javax.swing.JButton();
        btn_deleteLanguages = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        List_Languages = new javax.swing.JList<>();
        btn_NextStepHobbies = new javax.swing.JButton();
        btn_BackStepPersonal = new javax.swing.JButton();
        pnl_hobbies = new JPanelGradient();
        jPanel3 = new JPanelGradient();
        lbl_HobbiesIcon = new javax.swing.JLabel();
        lbl_FinishIcon = new javax.swing.JLabel();
        btn_FinishCv = new javax.swing.JButton();
        lbl_IconHobbies = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        List_InterestAndHobbies = new javax.swing.JList<>();
        comboBoc_Hobbies = new javax.swing.JComboBox<>();
        btn_addHobbies = new javax.swing.JButton();
        btn_deleteHobbies = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridLayout());

        lbl_firstname.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbl_firstname.setText("First name");

        lbl_Surname.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbl_Surname.setText("Surname");

        lbl_Email.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbl_Email.setText("Email");

        txtField_Email.setEditable(false);

        lbl_phoneNumber.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbl_phoneNumber.setText("Phone number");

        lbl_city.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbl_city.setText("City/Town");

        cmboBox_Cities.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cmboBox_Cities.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Adana", "Adıyaman", "Afyon", "Ağrı", "Amasya", "Ankara", "Antalya", "Artvin", "Aydın", "Balıkesir", "Bilecik", "Bingöl", "Bitlis", "Bolu", "Burdur", "Bursa", "Çanakkale", "Çankırı", "Çorum", "Denizli", "Diyarbakır", "Edirne", "Elazığ", "Erzincan", "Erzurum", "Eskişehir", "Gaziantep", "Giresun", "Gümüşhane", "Hakkari", "Hatay", "Isparta", "İçel (Mersin)", "İstanbul", "İzmir", "Kars", "Kastamonu", "Kayseri", "Kırklareli", "Kırşehir", "Kocaeli", "Konya", "Kütahya", "Malatya", "Manisa", "K.maraş", "Mardin", "Muğla", "Muş", "Nevşehir", "Niğde", "Ordu", "Rize", "Sakarya", "Samsun", "Siirt", "Sinop", "Sivas", "Tekirdağ", "Tokat", "Trabzon", "Tunceli", "Şanlıurfa", "Uşak", "Van", "Yozgat", "Zonguldak", "Aksaray", "Bayburt", "Karaman", "Kırıkkale", "Batman", "Şırnak", "Bartın", "Ardahan", "Iğdır", "Yalova", "Karabük", "Kilis", "Osmaniye", "Düzce" }));

        lbl_DateOfBirth.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbl_DateOfBirth.setText("Date of birth");

        cmbBox_Day.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cmbBox_Day.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30" }));

        cmbBox_Months.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cmbBox_Months.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January\t", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));

        lbl_Gender.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbl_Gender.setText("Gender");

        rbtn_male.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        rbtn_male.setText("Male");

        rbtn_female.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        rbtn_female.setText("Female");

        cmbBox_Year.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cmbBox_Year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2002", "2001", "2000", "1999", "1998", "1997", "1996", "1995", "1994", "1993", "1992", "1991", "1990", "1989", "1988", "1987", "1986", "1985", "1984", "1983", "1982", "1981", "1980", "1980" }));

        btn_NextStepExperiences.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn_NextStepExperiences.setText("Next step >");
        btn_NextStepExperiences.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NextStepExperiencesActionPerformed(evt);
            }
        });

        jlabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\hasan\\Desktop\\FSMVÜ\\CV UYGULAMASI(FİNAL)\\name.png")); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\hasan\\Desktop\\FSMVÜ\\CV UYGULAMASI(FİNAL)\\aaaaemail.png")); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\hasan\\Desktop\\FSMVÜ\\CV UYGULAMASI(FİNAL)\\buildings.png")); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\hasan\\Desktop\\FSMVÜ\\CV UYGULAMASI(FİNAL)\\birthday.png")); // NOI18N

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\hasan\\Desktop\\FSMVÜ\\CV UYGULAMASI(FİNAL)\\name.png")); // NOI18N

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\hasan\\Desktop\\FSMVÜ\\CV UYGULAMASI(FİNAL)\\telephone.png")); // NOI18N

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\hasan\\Desktop\\FSMVÜ\\CV UYGULAMASI(FİNAL)\\lavatory.png")); // NOI18N

        lbl_age.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbl_age.setText("Age");

        lbl_ageIcon1.setIcon(new javax.swing.ImageIcon("C:\\Users\\hasan\\Desktop\\FSMVÜ\\CV UYGULAMASI(FİNAL)\\adult.png")); // NOI18N

        slider_age.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        slider_age.setMajorTickSpacing(5);
        slider_age.setMaximum(50);
        slider_age.setMinimum(18);
        slider_age.setValue(34);
        slider_age.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slider_ageStateChanged(evt);
            }
        });

        spinner_age.setModel(new javax.swing.SpinnerNumberModel(24, 18, 50, 1));
        spinner_age.setEnabled(false);

        btn_BacktoTheLoginFrame.setText("<<< Return to login screen");
        btn_BacktoTheLoginFrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BacktoTheLoginFrameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_PersonalInformationLayout = new javax.swing.GroupLayout(pnl_PersonalInformation);
        pnl_PersonalInformation.setLayout(pnl_PersonalInformationLayout);
        pnl_PersonalInformationLayout.setHorizontalGroup(
            pnl_PersonalInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_PersonalInformationLayout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addGroup(pnl_PersonalInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_PersonalInformationLayout.createSequentialGroup()
                        .addGroup(pnl_PersonalInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_ageIcon1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGroup(pnl_PersonalInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_PersonalInformationLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rbtn_male)
                                .addGap(47, 47, 47)
                                .addComponent(rbtn_female)
                                .addGap(29, 29, 29))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_PersonalInformationLayout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(pnl_PersonalInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnl_PersonalInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtField_firstName, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(pnl_PersonalInformationLayout.createSequentialGroup()
                                            .addGroup(pnl_PersonalInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lbl_DateOfBirth)
                                                .addGroup(pnl_PersonalInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addGroup(pnl_PersonalInformationLayout.createSequentialGroup()
                                                        .addComponent(lbl_Email)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(txtField_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_PersonalInformationLayout.createSequentialGroup()
                                                        .addComponent(lbl_city)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(cmboBox_Cities, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addGap(7, 7, 7)))
                                    .addGroup(pnl_PersonalInformationLayout.createSequentialGroup()
                                        .addComponent(lbl_age)
                                        .addGap(47, 47, 47)
                                        .addComponent(slider_age, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(52, 52, 52)
                                        .addComponent(spinner_age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                                .addGroup(pnl_PersonalInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(pnl_PersonalInformationLayout.createSequentialGroup()
                                        .addGroup(pnl_PersonalInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel12))
                                        .addGap(35, 35, 35)
                                        .addGroup(pnl_PersonalInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbl_Surname)
                                            .addComponent(lbl_phoneNumber)
                                            .addComponent(lbl_Gender))
                                        .addGap(30, 30, 30)
                                        .addGroup(pnl_PersonalInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtField_Surname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtField_phoneNumber, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(pnl_PersonalInformationLayout.createSequentialGroup()
                                        .addComponent(btn_BacktoTheLoginFrame)
                                        .addGap(30, 30, 30)
                                        .addComponent(btn_NextStepExperiences, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(pnl_PersonalInformationLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(pnl_PersonalInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_PersonalInformationLayout.createSequentialGroup()
                                .addGap(159, 159, 159)
                                .addComponent(cmbBox_Day, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cmbBox_Months, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(68, 68, 68)
                                .addComponent(cmbBox_Year, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnl_PersonalInformationLayout.createSequentialGroup()
                                .addComponent(lbl_firstname)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(50, 50, 50))
        );
        pnl_PersonalInformationLayout.setVerticalGroup(
            pnl_PersonalInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_PersonalInformationLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(pnl_PersonalInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtField_Surname, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Surname)
                    .addComponent(txtField_firstName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_firstname)
                    .addComponent(jlabel8)
                    .addComponent(jLabel10))
                .addGap(50, 50, 50)
                .addGroup(pnl_PersonalInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_PersonalInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtField_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_Email)
                        .addComponent(jLabel7))
                    .addGroup(pnl_PersonalInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_phoneNumber)
                        .addComponent(txtField_phoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11)))
                .addGroup(pnl_PersonalInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_PersonalInformationLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8))
                    .addGroup(pnl_PersonalInformationLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(pnl_PersonalInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addGroup(pnl_PersonalInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(rbtn_male)
                                .addComponent(rbtn_female)
                                .addComponent(lbl_Gender))
                            .addGroup(pnl_PersonalInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cmboBox_Cities, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl_city)))))
                .addGap(50, 50, 50)
                .addGroup(pnl_PersonalInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_PersonalInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmbBox_Year, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmbBox_Months, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmbBox_Day, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_DateOfBirth))
                    .addComponent(jLabel9))
                .addGap(41, 41, 41)
                .addGroup(pnl_PersonalInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnl_PersonalInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnl_PersonalInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_NextStepExperiences, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_BacktoTheLoginFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(lbl_age)
                        .addComponent(slider_age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(spinner_age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_PersonalInformationLayout.createSequentialGroup()
                        .addComponent(lbl_ageIcon1)
                        .addGap(19, 19, 19)))
                .addContainerGap(86, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnl_personalLayout = new javax.swing.GroupLayout(pnl_personal);
        pnl_personal.setLayout(pnl_personalLayout);
        pnl_personalLayout.setHorizontalGroup(
            pnl_personalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_personalLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnl_PersonalInformation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnl_personalLayout.setVerticalGroup(
            pnl_personalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_personalLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnl_PersonalInformation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        tabbed_pane.addTab("Personal", pnl_personal);

        lbl_experiencesIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\hasan\\Desktop\\FSMVÜ\\CV UYGULAMASI(FİNAL)\\increase12.png")); // NOI18N

        btn_add.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn_add.setText("ADD");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        List_Experiences.setBorder(javax.swing.BorderFactory.createTitledBorder("Programming Languages"));
        List_Experiences.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jScrollPane1.setViewportView(List_Experiences);

        btn_delete.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn_delete.setText("DELETE");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        lbl_languagesIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\hasan\\Desktop\\FSMVÜ\\CV UYGULAMASI(FİNAL)\\translation.png")); // NOI18N

        btn_addLanguages.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn_addLanguages.setText("ADD");
        btn_addLanguages.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addLanguagesActionPerformed(evt);
            }
        });

        btn_deleteLanguages.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn_deleteLanguages.setText("DELETE");
        btn_deleteLanguages.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteLanguagesActionPerformed(evt);
            }
        });

        List_Languages.setBorder(javax.swing.BorderFactory.createTitledBorder("Languages"));
        List_Languages.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jScrollPane2.setViewportView(List_Languages);

        btn_NextStepHobbies.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn_NextStepHobbies.setText("Next Step >");
        btn_NextStepHobbies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NextStepHobbiesActionPerformed(evt);
            }
        });

        btn_BackStepPersonal.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn_BackStepPersonal.setText("< Previous Step");
        btn_BackStepPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BackStepPersonalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_BackStepPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btn_add, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_delete, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                                .addComponent(comboBox_experiences, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(lbl_experiencesIcon)))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(lbl_languagesIcon))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_deleteLanguages, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_addLanguages, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboBox_languages, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_NextStepHobbies, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(50, 50, 50))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 29, Short.MAX_VALUE)
                                .addComponent(lbl_languagesIcon)
                                .addGap(27, 27, 27)
                                .addComponent(comboBox_languages, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(btn_addLanguages, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(btn_deleteLanguages, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(lbl_experiencesIcon)
                        .addGap(27, 27, 27)
                        .addComponent(comboBox_experiences, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_NextStepHobbies, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_BackStepPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout pnl_experiencesLayout = new javax.swing.GroupLayout(pnl_experiences);
        pnl_experiences.setLayout(pnl_experiencesLayout);
        pnl_experiencesLayout.setHorizontalGroup(
            pnl_experiencesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1065, Short.MAX_VALUE)
            .addGroup(pnl_experiencesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnl_experiencesLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        pnl_experiencesLayout.setVerticalGroup(
            pnl_experiencesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 505, Short.MAX_VALUE)
            .addGroup(pnl_experiencesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnl_experiencesLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        tabbed_pane.addTab("Experiences", pnl_experiences);

        lbl_HobbiesIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\hasan\\Desktop\\FSMVÜ\\CV UYGULAMASI(FİNAL)\\mental-health.png")); // NOI18N

        lbl_FinishIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\hasan\\Desktop\\FSMVÜ\\CV UYGULAMASI(FİNAL)\\finish.png")); // NOI18N

        btn_FinishCv.setText("FINISH CV");
        btn_FinishCv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_FinishCvActionPerformed(evt);
            }
        });

        lbl_IconHobbies.setIcon(new javax.swing.ImageIcon("C:\\Users\\hasan\\Desktop\\FSMVÜ\\CV UYGULAMASI(FİNAL)\\lifestyle.png")); // NOI18N

        List_InterestAndHobbies.setBorder(javax.swing.BorderFactory.createTitledBorder("Interest And Hobbies"));
        List_InterestAndHobbies.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jScrollPane3.setViewportView(List_InterestAndHobbies);

        comboBoc_Hobbies.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        btn_addHobbies.setText("ADD");
        btn_addHobbies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addHobbiesActionPerformed(evt);
            }
        });

        btn_deleteHobbies.setText("DELETE");
        btn_deleteHobbies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteHobbiesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lbl_HobbiesIcon)
                        .addGap(60, 60, 60)
                        .addComponent(lbl_IconHobbies))
                    .addComponent(btn_addHobbies, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboBoc_Hobbies, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_deleteHobbies, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(56, 56, 56)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_FinishIcon)
                    .addComponent(btn_FinishCv, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(121, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_IconHobbies)
                                    .addComponent(lbl_HobbiesIcon))
                                .addGap(50, 50, 50)
                                .addComponent(comboBoc_Hobbies, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addComponent(btn_addHobbies, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_deleteHobbies, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(lbl_FinishIcon)
                        .addGap(67, 67, 67)
                        .addComponent(btn_FinishCv, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnl_hobbiesLayout = new javax.swing.GroupLayout(pnl_hobbies);
        pnl_hobbies.setLayout(pnl_hobbiesLayout);
        pnl_hobbiesLayout.setHorizontalGroup(
            pnl_hobbiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1065, Short.MAX_VALUE)
            .addGroup(pnl_hobbiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnl_hobbiesLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        pnl_hobbiesLayout.setVerticalGroup(
            pnl_hobbiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 505, Short.MAX_VALUE)
            .addGroup(pnl_hobbiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnl_hobbiesLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        tabbed_pane.addTab("Interest and Hobbies", pnl_hobbies);

        getContentPane().add(tabbed_pane);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    String birthday;
    String city;
    int age;
    char gender;
    private void btn_NextStepExperiencesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_NextStepExperiencesActionPerformed
        // TODO add your handling code here:

        Matcher matcher;

        //I checked that the fields are filled in as desired
        //this field cannot be empty...
        if (txtField_firstName.getText().isEmpty()) {

            JOptionPane.showMessageDialog(null, "Please fill in the First name area.", "Error", JOptionPane.ERROR_MESSAGE);
            return;

        } else {
            matcher = Pattern.compile("^[a-zA-z]{3,15}$").matcher(txtField_firstName.getText());
            if (!matcher.find()) {
                JOptionPane.showMessageDialog(null, "First name must be leat 3 maximum 15 character and no number \n Your first name must be like mehmet or Mehmet", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            } else {

                if (txtField_Surname.getText().isEmpty()) {

                    JOptionPane.showMessageDialog(null, "Please fill in the  surname area.", "Error", JOptionPane.ERROR_MESSAGE);
                    return;

                } else {
                    matcher = Pattern.compile("^[a-zA-z]{2,20}$").matcher(txtField_firstName.getText());
                    if (!matcher.find()) {
                        JOptionPane.showMessageDialog(null, "Surname must be leat 2 maximum 20 character and no number \n Your Surname must be like ak or Ak", "Error", JOptionPane.ERROR_MESSAGE);
                        return;
                    } else {
                        if (txtField_phoneNumber.getText().isEmpty()) {
                            JOptionPane.showMessageDialog(null, "Please fill in the  phone number area.", "Error", JOptionPane.ERROR_MESSAGE);
                            return;
                        } else {
                            matcher = Pattern.compile("^(\\+\\d{1,3}( )?)?((\\(\\d{3}\\))|\\d{3})[- .]?\\d{3}[- .]?\\d{4}$").matcher(txtField_phoneNumber.getText());
                            if (!matcher.find()) {
                                JOptionPane.showMessageDialog(null, "you must first enter the country code and then 10 digits \n Your phone number must be like \n+123 (202) 555-0125\n+12 (202) 555-0125\n+1 (202) 555-0125", "Error", JOptionPane.ERROR_MESSAGE);
                                return;
                            } else {
                                birthday = "" + cmbBox_Day.getSelectedItem() + "/" + cmbBox_Months.getSelectedItem() + "/" + cmbBox_Year.getSelectedItem();
                                city = "" + cmboBox_Cities.getSelectedItem();
                                age = slider_age.getValue();

                                if (rbtn_female.isSelected() || rbtn_male.isSelected()) {
                                    if (rbtn_female.isSelected()) {
                                        gender = 'F';
                                    } else {
                                        gender = 'M';
                                    }

                                } else {
                                    JOptionPane.showMessageDialog(null, "please select a gender", "Error", JOptionPane.ERROR_MESSAGE);
                                    return;
                                }

                                //to switch to the next tabbedpane screen
                                tabbed_pane.setSelectedIndex(1);
                            }
                        }
                    }
                }
            }
        }

    }//GEN-LAST:event_btn_NextStepExperiencesActionPerformed

    private void slider_ageStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slider_ageStateChanged
        // TODO add your handling code here:
        spinner_age.setValue(slider_age.getValue());
    }//GEN-LAST:event_slider_ageStateChanged

    private void btn_BacktoTheLoginFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BacktoTheLoginFrameActionPerformed
        // TODO add your handling code here:
        //// When Return to login screen is clicked, to close this frame and return to the main login screen.
        LoginFrame LoginFrame = new LoginFrame();
        LoginFrame.setVisible(true);
        LoginFrame.pack();
        LoginFrame.setLocationRelativeTo(null);
        LoginFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_btn_BacktoTheLoginFrameActionPerformed

    DefaultListModel listModel = new DefaultListModel();
    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        // TODO add your handling code here

        for (int i = 0; i < List_Experiences.getModel().getSize(); i++) {

            if (List_Experiences.getModel().getElementAt(i) == comboBox_experiences.getSelectedItem()) {

                JOptionPane.showMessageDialog(null, "The experience you want to add is available in the list", "Error", JOptionPane.ERROR_MESSAGE);
                listModel.remove(i);
                return;
            }

        }
        listModel.addElement(comboBox_experiences.getSelectedItem());
        List_Experiences.setModel(listModel);
    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        // TODO add your handling code here:
        listModel.removeElementAt(List_Experiences.getSelectedIndex());
    }//GEN-LAST:event_btn_deleteActionPerformed

     DefaultListModel listModelLanguages = new DefaultListModel();
    private void btn_addLanguagesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addLanguagesActionPerformed

        for (int i = 0; i < List_Languages.getModel().getSize(); i++) {

            if (List_Languages.getModel().getElementAt(i) == comboBox_languages.getSelectedItem()) {

                JOptionPane.showMessageDialog(null, "The languages you want to add is available in the list", "Error", JOptionPane.ERROR_MESSAGE);
                listModelLanguages.remove(i);
                return;
            }

        }
        listModelLanguages.addElement(comboBox_languages.getSelectedItem());
        List_Languages.setModel(listModelLanguages);
    }//GEN-LAST:event_btn_addLanguagesActionPerformed

    private void btn_deleteLanguagesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteLanguagesActionPerformed

        listModelLanguages.removeElementAt(List_Languages.getSelectedIndex());
    }//GEN-LAST:event_btn_deleteLanguagesActionPerformed

    private void btn_NextStepHobbiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_NextStepHobbiesActionPerformed
        // TODO add your handling code here:
        //to switch to the next tabbedpane screen
        tabbed_pane.setSelectedIndex(2);
    }//GEN-LAST:event_btn_NextStepHobbiesActionPerformed

    private void btn_BackStepPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BackStepPersonalActionPerformed
        // TODO add your handling code here:
        //to switch to the next tabbedpane screen
        tabbed_pane.setSelectedIndex(0);
    }//GEN-LAST:event_btn_BackStepPersonalActionPerformed

     //I made these methods to get the information held in jLists as a single string value.
    String user_languages = user_languages();

    public String user_languages() {
        String str = "";
        for (int i = 0; i < List_Languages.getModel().getSize(); i++) {

            str += List_Languages.getModel().getElementAt(i) + ", ";

        }

        return str;
    }

    String user_hobbies = user_hobbies();

    public String user_hobbies() {
        String str = "";
        for (int i = 0; i < List_InterestAndHobbies.getModel().getSize(); i++) {

            str += List_InterestAndHobbies.getModel().getElementAt(i) + ", ";

        }

        return str;
    }

    String user_experiences = user_experiences();

    public String user_experiences() {
        String str = "";
        for (int i = 0; i < List_Experiences.getModel().getSize(); i++) {

            str += List_Experiences.getModel().getElementAt(i) + ", ";

        }

        return str;
    }

    private void btn_FinishCvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_FinishCvActionPerformed
        // TODO add your handling code here:

        if (txtField_firstName.getText().isEmpty()) {

            JOptionPane.showMessageDialog(null, "Please fill in the First name area.", "Error", JOptionPane.ERROR_MESSAGE);
            return;

        } else {

            if (txtField_Surname.getText().isEmpty()) {

                JOptionPane.showMessageDialog(null, "Please fill in the  surname area.", "Error", JOptionPane.ERROR_MESSAGE);
                return;

            } else {

                if (txtField_phoneNumber.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Please fill in the  phone number area.", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                } else {

                    // everything is correct and save database, give information...
                    Connection conn = null;

                    try {

                        //I did the insert operations.
                        conn = DriverManager.getConnection("jdbc:derby://localhost:1527/CvAppDB", "sa", "as");
                        PreparedStatement stmt = conn.prepareStatement("INSERT INTO CV_INFO (FIRST_NAME, SURNAME, EMAIL,PHONE_NUMBER,CITY_TOWN,GENDER,DATE_OF_BIRTH,EXPERIENCES,USER_LANGUAGES,USER_HOBBIES,USER_AGE) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)");

                        stmt.setString(1, txtField_firstName.getText());
                        stmt.setString(2, txtField_Surname.getText());
                        stmt.setString(3, txtField_Email.getText());
                        stmt.setString(4, txtField_phoneNumber.getText());
                        stmt.setString(5, cmboBox_Cities.getSelectedItem().toString());
                        stmt.setString(6, String.valueOf(gender));//internetteb buldum hatalı olabilir.
                        stmt.setString(7, birthday);
                        stmt.setString(8, user_experiences);
                        stmt.setString(9, user_languages);
                        stmt.setString(10, user_hobbies);
                        stmt.setInt(8, age);

                    } catch (Exception ex) {

                    }

                }

            }

        }

    }//GEN-LAST:event_btn_FinishCvActionPerformed
DefaultListModel listModelHobbies = new DefaultListModel();
    private void btn_addHobbiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addHobbiesActionPerformed
        // TODO add your handling code here:
        for (int i = 0; i < List_InterestAndHobbies.getModel().getSize(); i++) {

            if (List_InterestAndHobbies.getModel().getElementAt(i) == comboBoc_Hobbies.getSelectedItem()) {

                JOptionPane.showMessageDialog(null, "The hobbies you want to add is available in the list", "Error", JOptionPane.ERROR_MESSAGE);
                listModelHobbies.remove(i);
                return;
            }

        }
        listModelHobbies.addElement(comboBoc_Hobbies.getSelectedItem());
        List_InterestAndHobbies.setModel(listModelHobbies);
    }//GEN-LAST:event_btn_addHobbiesActionPerformed

    private void btn_deleteHobbiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteHobbiesActionPerformed
        // TODO add your handling code here:
        listModelHobbies.removeElementAt(List_InterestAndHobbies.getSelectedIndex());
    }//GEN-LAST:event_btn_deleteHobbiesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CvCreate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CvCreate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CvCreate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CvCreate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CvCreate("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> List_Experiences;
    private javax.swing.JList<String> List_InterestAndHobbies;
    private javax.swing.JList<String> List_Languages;
    private javax.swing.JButton btn_BackStepPersonal;
    private javax.swing.JButton btn_BacktoTheLoginFrame;
    private javax.swing.JButton btn_FinishCv;
    private javax.swing.JButton btn_NextStepExperiences;
    private javax.swing.JButton btn_NextStepHobbies;
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_addHobbies;
    private javax.swing.JButton btn_addLanguages;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_deleteHobbies;
    private javax.swing.JButton btn_deleteLanguages;
    private javax.swing.JComboBox<String> cmbBox_Day;
    private javax.swing.JComboBox<String> cmbBox_Months;
    private javax.swing.JComboBox<String> cmbBox_Year;
    private javax.swing.JComboBox<String> cmboBox_Cities;
    private javax.swing.JComboBox<String> comboBoc_Hobbies;
    private javax.swing.JComboBox<String> comboBox_experiences;
    private javax.swing.JComboBox<String> comboBox_languages;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel jlabel8;
    private javax.swing.JLabel lbl_DateOfBirth;
    private javax.swing.JLabel lbl_Email;
    private javax.swing.JLabel lbl_FinishIcon;
    private javax.swing.JLabel lbl_Gender;
    private javax.swing.JLabel lbl_HobbiesIcon;
    private javax.swing.JLabel lbl_IconHobbies;
    private javax.swing.JLabel lbl_Surname;
    private javax.swing.JLabel lbl_age;
    private javax.swing.JLabel lbl_ageIcon1;
    private javax.swing.JLabel lbl_city;
    private javax.swing.JLabel lbl_experiencesIcon;
    private javax.swing.JLabel lbl_firstname;
    private javax.swing.JLabel lbl_languagesIcon;
    private javax.swing.JLabel lbl_phoneNumber;
    private javax.swing.JPanel pnl_PersonalInformation;
    private javax.swing.JPanel pnl_experiences;
    private javax.swing.JPanel pnl_hobbies;
    private javax.swing.JPanel pnl_personal;
    private javax.swing.JRadioButton rbtn_female;
    private javax.swing.JRadioButton rbtn_male;
    private javax.swing.JSlider slider_age;
    private javax.swing.JSpinner spinner_age;
    private javax.swing.JTabbedPane tabbed_pane;
    private javax.swing.JTextField txtField_Email;
    private javax.swing.JTextField txtField_Surname;
    private javax.swing.JTextField txtField_firstName;
    private javax.swing.JTextField txtField_phoneNumber;
    // End of variables declaration//GEN-END:variables
}
