/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.cvapp;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author hasan
 */
public class LoginFrame extends javax.swing.JFrame {

    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        initComponents();
        setTitle("Login Screen");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_loginBackground = new javax.swing.JPanel();
        btn_SignUp = new javax.swing.JButton();
        lbl_EmailIcon = new javax.swing.JLabel();
        lbl_passwordIcon = new javax.swing.JLabel();
        txtField_userEmail = new javax.swing.JTextField();
        txtField_userPassword = new javax.swing.JPasswordField();
        btn_Login = new javax.swing.JButton();
        lbl_ForgetPassword = new javax.swing.JLabel();
        lbl_CvIcon = new javax.swing.JLabel();
        lbl_backgroundPhoto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(750, 100));
        setMaximumSize(new java.awt.Dimension(540, 760));
        setMinimumSize(new java.awt.Dimension(540, 760));
        setPreferredSize(new java.awt.Dimension(540, 760));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        pnl_loginBackground.setBackground(new java.awt.Color(255, 255, 255));
        pnl_loginBackground.setMaximumSize(new java.awt.Dimension(540, 780));
        pnl_loginBackground.setMinimumSize(new java.awt.Dimension(540, 780));
        pnl_loginBackground.setPreferredSize(new java.awt.Dimension(540, 780));
        pnl_loginBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_SignUp.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btn_SignUp.setText("Sign Up");
        btn_SignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SignUpActionPerformed(evt);
            }
        });
        pnl_loginBackground.add(btn_SignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 310, -1));
        pnl_loginBackground.add(lbl_EmailIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, -1, -1));
        pnl_loginBackground.add(lbl_passwordIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, -1, -1));

        txtField_userEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtField_userEmailActionPerformed(evt);
            }
        });
        pnl_loginBackground.add(txtField_userEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 240, 32));
        pnl_loginBackground.add(txtField_userPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 240, 31));

        btn_Login.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btn_Login.setText("Login");
        btn_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LoginActionPerformed(evt);
            }
        });
        pnl_loginBackground.add(btn_Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 310, -1));

        lbl_ForgetPassword.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbl_ForgetPassword.setForeground(new java.awt.Color(255, 255, 255));
        lbl_ForgetPassword.setText("Forgot your password ?");
        lbl_ForgetPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_ForgetPasswordMouseClicked(evt);
            }
        });
        pnl_loginBackground.add(lbl_ForgetPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, -1, -1));
        pnl_loginBackground.add(lbl_CvIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, -1, -1));

        lbl_backgroundPhoto.setMaximumSize(new java.awt.Dimension(540, 760));
        lbl_backgroundPhoto.setMinimumSize(new java.awt.Dimension(540, 760));
        lbl_backgroundPhoto.setPreferredSize(new java.awt.Dimension(540, 760));
        pnl_loginBackground.add(lbl_backgroundPhoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 760));

        getContentPane().add(pnl_loginBackground);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_SignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SignUpActionPerformed

        // To open the registration screen and close this screen when clicking the sign up button ...
        NewRecordScreenFrame RegisterFrame = new NewRecordScreenFrame();
        RegisterFrame.setVisible(true);
        RegisterFrame.pack();
        RegisterFrame.setLocationRelativeTo(null);
        RegisterFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();


    }//GEN-LAST:event_btn_SignUpActionPerformed

    private void btn_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LoginActionPerformed
        // TODO add your handling code here:

        Matcher matcher;

        // User mail checks and I checked the desired regex.
        //this field cannot be empty...
        if (txtField_userEmail.getText().isEmpty()) {

            JOptionPane.showMessageDialog(null, "Please write your Email adress...", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        } else {
            //In the mail part, it should start with a letter and I want the user to enter a mail address in the format of mehmetak01@gmail.com.
            matcher = Pattern.compile("^([\\w][\\w\\d]+)@(gmail|hotmail)(.com)$").matcher(txtField_userEmail.getText());
            if (!matcher.find()) {
                JOptionPane.showMessageDialog(null, "Your Email address must be like mehmetak@hotmail or mehmetak01@gmail.com", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            } else {

                //Whether the mail and passwords entered in the login screen are in the database or not has been checked.
                try {
                    Connection conn = null;
                    Statement stmt_select = null;

                    conn = DriverManager.getConnection("jdbc:derby://localhost:1527/CvAppDB", "sa", "as");
                    String query_email = "select count(*) as adet from user_info where user_email='" + txtField_userEmail.getText() + "'";
                    stmt_select = conn.createStatement();

                    ResultSet rs_check_Email = stmt_select.executeQuery(query_email);
                    int email_count = 0;
                    while (rs_check_Email.next()) {
                        email_count = rs_check_Email.getInt("adet");
                    }
                    if (email_count == 0) {
                        JOptionPane.showMessageDialog(null, "The entered mail is not registered in the system.", "Error", JOptionPane.ERROR_MESSAGE);
                        return;
                    } else {

                        String query_password = "select count(*) as adet from USER_INFO  where user_password = '" + txtField_userPassword.getText() + "' and user_email='" + txtField_userEmail.getText() + "'";
                        ResultSet rs_check_pass = stmt_select.executeQuery(query_password);
                        int pass_count = 0;
                        while (rs_check_pass.next()) {
                            pass_count = rs_check_pass.getInt("adet");
                        }
                        if (pass_count == 0) {
                            JOptionPane.showMessageDialog(null, "Entered password is incorrect.", "Error", JOptionPane.ERROR_MESSAGE);
                            return;
                            //If the login information is correct, the create cv screen will open.
                        } else {
                            CvCreationScreen cv_create = new CvCreationScreen(txtField_userEmail.getText());
                            cv_create.setVisible(true);
                            cv_create.pack();
                            cv_create.setLocationRelativeTo(null);
                            cv_create.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                            this.dispose();
                        }
                    }

                } catch (Exception e) {
                    String hata = e.getMessage();
                }
            }

        }


    }//GEN-LAST:event_btn_LoginActionPerformed

    private void txtField_userEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtField_userEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtField_userEmailActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // I want to ask to users when the winwod closing...
        int SelectedOption = JOptionPane.showConfirmDialog(rootPane, "Are you sure you want to close the app?", "Warning", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);

        if (SelectedOption == JOptionPane.YES_OPTION) {
            this.dispose();
        }
        if (SelectedOption == JOptionPane.NO_OPTION) {
            this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        }
    }//GEN-LAST:event_formWindowClosing

    private void lbl_ForgetPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ForgetPasswordMouseClicked
        // To open the registration screen and close this screen when clicking forget password button ...
        SendCode send_code = new SendCode();
        send_code.setVisible(true);
        send_code.pack();
        send_code.setLocationRelativeTo(null);
        send_code.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_lbl_ForgetPasswordMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Login;
    private javax.swing.JButton btn_SignUp;
    private javax.swing.JLabel lbl_CvIcon;
    private javax.swing.JLabel lbl_EmailIcon;
    private javax.swing.JLabel lbl_ForgetPassword;
    private javax.swing.JLabel lbl_backgroundPhoto;
    private javax.swing.JLabel lbl_passwordIcon;
    private javax.swing.JPanel pnl_loginBackground;
    private javax.swing.JTextField txtField_userEmail;
    private javax.swing.JPasswordField txtField_userPassword;
    // End of variables declaration//GEN-END:variables
}
